server:
  port: 8084
  maxHttpHeaderSize: 102400
  servlet:
    context-path: /api
  error:
    include-exception: true
    include-message: always
  undertow:
    max-http-post-size: -1
spring:
  application:
    name: assessment-server
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  ##选用缓存类型
  redis:
    host: 127.0.0.1
    #    password:
    port: 6379
    database: 9
  cache:
    type: redis  #ehcache
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/graded?useUnicode=true&useSSL=true&useUnicode=true&characterEncoding=UTF-8
#    username: graded
#    password: root
    url: jdbc:mysql://localhost:3306/graded_assessment?useUnicode=true&useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml


markerhub:
  jwt:
    header: Authorization
    expire: 1800 #30分钟，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h

qiniu:
  accessKey: BGUpQznLLmK0W230OZBiAoaCuavRh-7OYSnLFdtT
  secretKey: x_OuqdffUQwKLDM0bhOJIA6Mv9Ac37qFe1g21ywb
  bucket: xpwgh
  fontUrl: https://xpwghoss.3dy.me/

